get {{url}}
###
get {{url}}/users 
###
get {{url}}/users/chloie
###
delete {{url}}/users/chloie
###
post {{url}}/users
Content-Type: application/json

{
  "fname": "new"
}

###
get {{url}}/restaurants
###
get {{url}}/restaurants/2334b925-802e-4161-b5dd-de53315c9325

###
POST {{url}}/login
Content-Type: application/json

{
  "email": "{{user_3}}",
  "password": "{{pass_3}}" 
}
###
POST {{url}}/login
Content-Type: application/json

{
  "email": "{{user_2}}",
  "password": "{{pass_2}}" 
}
###
POST {{url}}/login
Content-Type: application/json

{
  "email": "{{user_2}}",
  "password": "wrongpassword" 
}